# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
VAGRANT_VM_PROVIDER = "virtualbox"

Vagrant.configure(VAGRANTFILE_API_VERSION) do | config |

    config.vm.provision "shell", path: "script.sh"

    VM_COUNT = 6

    config.vm.provider :virtualbox do | vb |
        vb.customize ["modifyvm", :id, "--memory", "1024"]
        vb.customize ["modifyvm", :id, "--natnet1", "10.3/16"]
        vb.gui = false
    end

    (1..VM_COUNT).each do | machine_id |
        config.vm.define "poste#{machine_id}" do | server |
            server.vm.hostname = "poste#{machine_id}"
            server.vm.box = "centos/7"
            server.vm.network :private_network, ip: "192.102.10.10#{machine_id}"
            server.vm.provider :virtualbox do | vb |
                vb.name = "poste#{machine_id}"
            end

        end
    end
end
~    
